esec: main.o rappresentazione.o film.o rappresentazioni.o esibizione.o spettacolo.o spettacoli.o funzioni.o biglietto.o biglietti.o
	g++ -o main main.o rappresentazione.o film.o rappresentazioni.o esibizione.o spettacolo.o spettacoli.o funzioni.o biglietto.o biglietti.o
	
main.o: main.cpp
	g++ -c main.cpp
	
rappresentazione.o: rappresentazione.cpp
	g++ -c rappresentazione.cpp
	
film.o: film.cpp
	g++ -c film.cpp
	
rappresentazioni.o: rappresentazioni.cpp
	g++ -c rappresentazioni.cpp
	
esibizione.o: esibizione.cpp
	g++ -c esibizione.cpp
	
spettacolo.o: spettacolo.cpp
	g++ -c spettacolo.cpp

spettacoli.o: spettacoli.cpp
	g++ -c spettacoli.cpp
	
funzioni.o: funzioni.cpp
	g++ -c funzioni.cpp
	
biglietto.o: biglietto.cpp
	g++ -c biglietto.cpp
	
biglietti.o: biglietti.cpp
	g++ -c biglietti.cpp
